#include <stdio.h>
#include <stdlib.h>
#include <sys/types.h>
#include <errno.h>
#include <unistd.h>
#include <fcntl.h>
#include <string.h>
#include <signal.h>
#include <stdint.h>
#include <sys/stat.h>
#include <sys/mman.h>
#include <sys/shm.h>
#include <sys/wait.h>
#include <pthread.h>
#include <bits/pthreadtypes.h>
#include <setjmp.h>
#include <stdbool.h>
#include <bits/pthread_stack_min.h>